let nameOfTheGame;
let gameDescription;
let gameVersion;
let theNameOfTheMainCharacterOfTheGame;
let nameOfTheGameDeveloper;
let theProgrammingLanguageInWhichTheGameIsWritten;
let versionOfTheProgrammingLanguageInWhichTheGameIsWritten;
let theNameOfTheMapOnWhichTheGameTakesPlace;
let gameDeveloperWebsite;
let InterfaceLanguage;

